
/*
* THIS FILE WAS AUTOMATICALLY GENERATED, DO NOT EDIT.
*
* This file was generated by the make_dbus.go script.
*/
#ifndef __AUTO_GEN_DBUS_DBUS_dock
#define __AUTO_GEN_DBUS_DBUS_dock
#include <glib.h>
void setup_dock_dbus_service();


void dbus_set_desktop_focused(gboolean arg0);



void dbus_launcher_hide();



void dbus_dock_daemon_update_hide_state();

void dbus_dock_daemon_cancel_toggle_show();

#endif