
/*
* THIS FILE WAS AUTOMATICALLY GENERATED, DO NOT EDIT.
*
* This file was generated by the make_dbus.go script.
*/
#ifndef __AUTO_GEN_DBUS_DBUS_launcher
#define __AUTO_GEN_DBUS_DBUS_launcher
#include <glib.h>
void setup_launcher_dbus_service();


void dbus_launcher_show();

void dbus_launcher_hide();

void dbus_launcher_toggle();

#endif