
/*
* THIS FILE WAS AUTOMATICALLY GENERATED, DO NOT EDIT.
*
* This file was generated by the make_dbus.go script.
*/
#ifndef __AUTO_GEN_DBUS_DBUS_desktop
#define __AUTO_GEN_DBUS_DBUS_desktop
#include <glib.h>
void setup_desktop_dbus_service();
#endif