
/*
* THIS FILE WAS AUTOMATICALLY GENERATED, DO NOT EDIT.
*
* This file was generated by the make_dbus.go script.
*/
#include <glib.h>
#include <gio/gio.h>

static int _service_owner_id = 0;
static GDBusInterfaceInfo * interface_info = NULL;

void desktop_focus_changed(gboolean) __attribute__((weak));

static void _bus_method_call (GDBusConnection * connection,
                 const gchar * sender, const gchar * object_path, const gchar * interface,
                 const gchar * method, GVariant * params,
                 GDBusMethodInvocation * invocation, gpointer user_data)
{
        (void)connection;
        (void)sender;
        (void)object_path;
        (void)interface;
        (void)user_data;
        (void)params;
        GVariant * retval = NULL;
        if (0) { 
        } else if (&desktop_focus_changed != 0 && g_strcmp0(method, "FocusChanged") == 0) {
    
        gboolean arg0;
    
    g_variant_get(params, "(b)", &arg0);

     desktop_focus_changed(arg0);

    
        g_dbus_method_invocation_return_value (invocation, retval);
        return;
    
    } else {
        g_dbus_method_invocation_return_dbus_error (invocation,
                "com.deepin.dde.desktop.Error",
                "Can't find this method");
        return;
    }

}
static void _on_bus_acquired (GDBusConnection * connection, const gchar * name, gpointer user_data)
{
    (void)name;
    static GDBusInterfaceVTable interface_table = {
        method_call:   _bus_method_call,
        get_property:   NULL, /* No properties */
        set_property:   NULL  /* No properties */
    };
    GError* error = NULL;
    g_dbus_connection_register_object (connection,
            "/com/deepin/dde/desktop",
            interface_info,
            &interface_table,
            user_data,
            NULL,
            &error);

    if (error != NULL) {
        g_critical ("Unable to register the object to DBus: %s", error->message);
        g_error_free (error);
        g_bus_unown_name (_service_owner_id);
    }
}

void
setup_desktop_dbus_service()
{
    const char* xml = "<?xml version=\"1.0\"?>"
"<node>"
"<interface name=\"com.deepin.dde.desktop\">"
"       <method name=\"FocusChanged\">"
"             <arg name=\"value\" type=\"b\" direction=\"in\"></arg>"
"       </method>" 
"       <signal name=\"ItemUpdate\">"
"       </signal>"
"       <signal name=\"RichdirCreate\">"
"       </signal>"
"</interface>"
"</node>";

    GError* error = NULL;
    GDBusNodeInfo * node_info = g_dbus_node_info_new_for_xml (xml, &error);
    if (error != NULL) {
        g_critical ("Unable to parse interface xml: %s", error->message);
        g_error_free (error);
    }

    interface_info = g_dbus_node_info_lookup_interface (node_info, "com.deepin.dde.desktop");
    /*g_dbus_node_info_unref(node_info);*/
    if (interface_info == NULL) {
        g_critical ("Unable to find interface \"com.deepin.dde.desktop\"");
    }

    _service_owner_id = g_bus_own_name (G_BUS_TYPE_SESSION,
            "com.deepin.dde.desktop",
            G_BUS_NAME_OWNER_FLAGS_NONE,
            _on_bus_acquired,
            NULL,
            NULL,
            NULL,
            NULL);
}
